// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenIM.Proto {

  /// <summary>Holder for reflection information generated from error.proto</summary>
  public static partial class ErrorReflection {

    #region Descriptor
    /// <summary>File descriptor for error.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtlcnJvci5wcm90bxIQb3BlbmltLnNkay5lcnJvciqQCwoJRXJyb3JDb2Rl",
            "EgsKB05vRXJyb3IQABITCg5TZXJ2ZXJJbnRlcm5hbBD0AxIJCgRBcmdzEOkH",
            "EhEKDE5vUGVybWlzc2lvbhDqBxIRCgxEdXBsaWNhdGVLZXkQ6wcSEwoOUmVj",
            "b3JkTm90Rm91bmQQ7AcSEQoMVG9rZW5FeHBpcmVkEN0LEhEKDFRva2VuSW52",
            "YWxpZBDeCxITCg5Ub2tlbk1hbGZvcm1lZBDfCxIVChBUb2tlbk5vdFZhbGlk",
            "WWV0EOALEhEKDFRva2VuVW5rbm93bhDhCxIQCgtUb2tlbktpY2tlZBDiCxIS",
            "Cg1Ub2tlbk5vdEV4aXN0EOMLEg8KClNka05ldHdvcmsQkE4SFgoRU2RrTmV0",
            "d29ya1RpbWVvdXQQkU4SDAoHU2RrQXJncxCSThIbChZTZGtDdHhEZWFkbGlu",
            "ZUV4Y2VlZGVkEJNOEh8KGlNka1Jlc291cmNlTG9hZE5vdENvbXBsZXRlEJRO",
            "EhMKDlNka1Vua25vd25Db2RlEJVOEhAKC1Nka0ludGVybmFsEJZOEhQKD1Nk",
            "a0Z1bmNOb3RGb3VuZBCXThIPCgpTZGtOb3RJbml0EJhOEhAKC1Nka05vdExv",
            "Z2luEJlOEhYKEVNka1VzZXJJRE5vdEZvdW5kEPROEhAKC1Nka0xvZ2luT3V0",
            "EPVOEhMKDlNka0xvZ2luUmVwZWF0EPZOEhQKD1Nka0ZpbGVOb3RGb3VuZBDY",
            "TxIYChNTZGtNc2dEZUNvbXByZXNzaW9uENlPEhkKFFNka01zZ0RlY29kZUJp",
            "bmFyeVdzENpPEh8KGlNka01zZ0JpbmFyeVR5cGVOb3RTdXBwb3J0ENtPEhEK",
            "DFNka01zZ1JlcGVhdBDcTxIgChtTZGtNc2dDb250ZW50VHlwZU5vdFN1cHBv",
            "cnQQ3U8SEwoOU2RrTXNnSGFzTm9TZXEQ3k8SFQoQU2RrTm90U3VwcG9ydE9w",
            "dBC9UBIWChFTZGtOb3RTdXBwb3J0VHlwZRC+UBITCg5TZGtVbnJlYWRDb3Vu",
            "dBC/UBIXChJTZGtHcm91cElETm90Rm91bmQQoFESEQoMU2RrR3JvdXBUeXBl",
            "EKFREhYKEVNydlVzZXJJRE5vdEZvdW5kEM0IEhkKFFNydlJlZ2lzdGVyZWRB",
            "bHJlYWR5EM4IEhcKElNydkdyb3VwSUROb3RGb3VuZBCxCRIWChFTcnZHcm91",
            "cElERXhpc3RlZBCyCRIVChBTcnZOb3RJbkdyb3VwWWV0ELMJEhgKE1NydkRp",
            "c21pc3NlZEFscmVhZHkQtAkSGwoWU3J2R3JvdXBUeXBlTm90U3VwcG9ydBC1",
            "CRIbChZTcnZHcm91cFJlcXVlc3RIYW5kbGVkELYJEhkKFFNydkNhbk5vdEFk",
            "ZFlvdXJzZWxmEJUKEhUKEFNydkJsb2NrZWRCeVBlZXIQlgoSFgoRU3J2Tm90",
            "UGVlcnNGcmllbmQQlwoSGwoWU3J2UmVsYXRpb25zaGlwQWxyZWFkeRCYChId",
            "ChhTcnZNZXNzYWdlSGFzUmVhZERpc2FibGUQ+QoSFAoPU3J2TXV0ZWRJbkdy",
            "b3VwEPoKEhIKDVNydk11dGVkR3JvdXAQ+woSGAoTU3J2TXNnQWxyZWFkeVJl",
            "dm9rZRD8ChIbChZTcnZDb25uT3Zlck1heE51bUxpbWl0EMEMEhAKC1NydkNv",
            "bm5BcmdzEMIMEg8KClNydlB1c2hNc2cQwwwSGQoUU3J2SU9TQmFja2dyb3Vu",
            "ZFB1c2gQxAwSGwoWU3J2RmlsZVVwbG9hZGVkRXhwaXJlZBClDRIRCgtTcnZE",
            "YXRhYmFzZRCSvwUSEAoKU3J2TmV0d29yaxCUvwUSDQoHU3J2RGF0YRCXvwUS",
            "EQoLU3J2Q2FsbGJhY2sQgPEEQkpaNmdpdGh1Yi5jb20vb3Blbmltc2RrL29w",
            "ZW5pbS1zZGstY29yZS92My9wcm90by9nby9lcnJvcqoCDE9wZW5JTS5Qcm90",
            "b7oCAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OpenIM.Proto.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    /// <summary>
    /// NoError is the zero value of ErrorCode.
    /// </summary>
    [pbr::OriginalName("NoError")] NoError = 0,
    /// <summary>
    /// Common error codes.
    /// </summary>
    [pbr::OriginalName("ServerInternal")] ServerInternal = 500,
    [pbr::OriginalName("Args")] Args = 1001,
    [pbr::OriginalName("NoPermission")] NoPermission = 1002,
    [pbr::OriginalName("DuplicateKey")] DuplicateKey = 1003,
    [pbr::OriginalName("RecordNotFound")] RecordNotFound = 1004,
    [pbr::OriginalName("TokenExpired")] TokenExpired = 1501,
    [pbr::OriginalName("TokenInvalid")] TokenInvalid = 1502,
    [pbr::OriginalName("TokenMalformed")] TokenMalformed = 1503,
    [pbr::OriginalName("TokenNotValidYet")] TokenNotValidYet = 1504,
    [pbr::OriginalName("TokenUnknown")] TokenUnknown = 1505,
    [pbr::OriginalName("TokenKicked")] TokenKicked = 1506,
    [pbr::OriginalName("TokenNotExist")] TokenNotExist = 1507,
    [pbr::OriginalName("SdkNetwork")] SdkNetwork = 10000,
    [pbr::OriginalName("SdkNetworkTimeout")] SdkNetworkTimeout = 10001,
    [pbr::OriginalName("SdkArgs")] SdkArgs = 10002,
    [pbr::OriginalName("SdkCtxDeadlineExceeded")] SdkCtxDeadlineExceeded = 10003,
    [pbr::OriginalName("SdkResourceLoadNotComplete")] SdkResourceLoadNotComplete = 10004,
    [pbr::OriginalName("SdkUnknownCode")] SdkUnknownCode = 10005,
    [pbr::OriginalName("SdkInternal")] SdkInternal = 10006,
    [pbr::OriginalName("SdkFuncNotFound")] SdkFuncNotFound = 10007,
    [pbr::OriginalName("SdkNotInit")] SdkNotInit = 10008,
    [pbr::OriginalName("SdkNotLogin")] SdkNotLogin = 10009,
    [pbr::OriginalName("SdkUserIDNotFound")] SdkUserIdnotFound = 10100,
    [pbr::OriginalName("SdkLoginOut")] SdkLoginOut = 10101,
    [pbr::OriginalName("SdkLoginRepeat")] SdkLoginRepeat = 10102,
    [pbr::OriginalName("SdkFileNotFound")] SdkFileNotFound = 10200,
    [pbr::OriginalName("SdkMsgDeCompression")] SdkMsgDeCompression = 10201,
    [pbr::OriginalName("SdkMsgDecodeBinaryWs")] SdkMsgDecodeBinaryWs = 10202,
    [pbr::OriginalName("SdkMsgBinaryTypeNotSupport")] SdkMsgBinaryTypeNotSupport = 10203,
    [pbr::OriginalName("SdkMsgRepeat")] SdkMsgRepeat = 10204,
    [pbr::OriginalName("SdkMsgContentTypeNotSupport")] SdkMsgContentTypeNotSupport = 10205,
    [pbr::OriginalName("SdkMsgHasNoSeq")] SdkMsgHasNoSeq = 10206,
    [pbr::OriginalName("SdkNotSupportOpt")] SdkNotSupportOpt = 10301,
    [pbr::OriginalName("SdkNotSupportType")] SdkNotSupportType = 10302,
    [pbr::OriginalName("SdkUnreadCount")] SdkUnreadCount = 10303,
    [pbr::OriginalName("SdkGroupIDNotFound")] SdkGroupIdnotFound = 10400,
    [pbr::OriginalName("SdkGroupType")] SdkGroupType = 10401,
    [pbr::OriginalName("SrvUserIDNotFound")] SrvUserIdnotFound = 1101,
    [pbr::OriginalName("SrvRegisteredAlready")] SrvRegisteredAlready = 1102,
    [pbr::OriginalName("SrvGroupIDNotFound")] SrvGroupIdnotFound = 1201,
    [pbr::OriginalName("SrvGroupIDExisted")] SrvGroupIdexisted = 1202,
    [pbr::OriginalName("SrvNotInGroupYet")] SrvNotInGroupYet = 1203,
    [pbr::OriginalName("SrvDismissedAlready")] SrvDismissedAlready = 1204,
    [pbr::OriginalName("SrvGroupTypeNotSupport")] SrvGroupTypeNotSupport = 1205,
    [pbr::OriginalName("SrvGroupRequestHandled")] SrvGroupRequestHandled = 1206,
    [pbr::OriginalName("SrvCanNotAddYourself")] SrvCanNotAddYourself = 1301,
    [pbr::OriginalName("SrvBlockedByPeer")] SrvBlockedByPeer = 1302,
    [pbr::OriginalName("SrvNotPeersFriend")] SrvNotPeersFriend = 1303,
    [pbr::OriginalName("SrvRelationshipAlready")] SrvRelationshipAlready = 1304,
    [pbr::OriginalName("SrvMessageHasReadDisable")] SrvMessageHasReadDisable = 1401,
    [pbr::OriginalName("SrvMutedInGroup")] SrvMutedInGroup = 1402,
    [pbr::OriginalName("SrvMutedGroup")] SrvMutedGroup = 1403,
    [pbr::OriginalName("SrvMsgAlreadyRevoke")] SrvMsgAlreadyRevoke = 1404,
    [pbr::OriginalName("SrvConnOverMaxNumLimit")] SrvConnOverMaxNumLimit = 1601,
    [pbr::OriginalName("SrvConnArgs")] SrvConnArgs = 1602,
    [pbr::OriginalName("SrvPushMsg")] SrvPushMsg = 1603,
    [pbr::OriginalName("SrvIOSBackgroundPush")] SrvIosbackgroundPush = 1604,
    [pbr::OriginalName("SrvFileUploadedExpired")] SrvFileUploadedExpired = 1701,
    [pbr::OriginalName("SrvDatabase")] SrvDatabase = 90002,
    [pbr::OriginalName("SrvNetwork")] SrvNetwork = 90004,
    [pbr::OriginalName("SrvData")] SrvData = 90007,
    [pbr::OriginalName("SrvCallback")] SrvCallback = 80000,
  }

  #endregion

}

#endregion Designer generated code
